import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Home, MessageCircle, User } from 'lucide-react';
import { FloatingNav } from '@/components/ui/floating-navbar';
import { BackgroundBeamsWithCollision } from '@/components/ui/background-beams-with-collision';
import ParticlesBackground from '@/components/ui/particles-background';
const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const navItems = [
	{
		name: 'Home',
		link: '/',
		icon: <Home className='h-4 w-4 text-neutral-500 dark:text-white' />,
	},
	{
		name: 'About',
		link: '/about',
		icon: <User className='h-4 w-4 text-neutral-500 dark:text-white' />,
	},
	{
		name: 'Contact',
		link: '/contact',
		icon: (
			<MessageCircle className='h-4 w-4 text-neutral-500 dark:text-white' />
		),
	},
];

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div className='min-h-screen bg-white text-black dark:bg-black dark:text-white relative overflow-hidden'>
					<BackgroundBeamsWithCollision>
						{children}
					</BackgroundBeamsWithCollision>
					<FloatingNav navItems={navItems} />
				</div>
			</body>
		</html>
	);
}
